name: Download new schema

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 16 * * *' # Runs every day at 16:00 UTC / 5 PM CET
  workflow_dispatch:
    
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set environment variables
        run: echo SCHEMA_PATH=$(pwd) >> $GITHUB_ENV
      
      - name: Create Dir
        run: mkdir -p files/localized
    
      - name: Compare & Download schema
        id: compare
        run: |
          declare -a Formats=("json" "vdf" "xml")
          declare -a Languages=("en" "da" "nl" "fi" "fr" "de" "hu" "it" "ja" "ko" "no" "pl" "pt" "pt_BR" "ro" "ru" "zh" "es" "sv" "zh2" "tr")

          wget -U "TF2-Up-To-Date-Schema-Updater" "https://api.steampowered.com/IEconItems_440/GetSchemaItems/v1?key=${{ secrets.STEAM_API_KEY }}&format=json" -O "item_schema_json_test.txt"

          rm item_schema_json_test.txt
          
          echo "files_same=true" >> $GITHUB_OUTPUT

          if [ -f item_schema_json.txt ] || cmp -s item_schema_json.txt item_schema_json_new.txt;
          then
            exit 0
          fi

          for format in "${Formats[@]}";
          do
            wget -U "TF2-Up-To-Date-Schema-Updater" "https://api.steampowered.com/IEconItems_440/GetSchemaItems/v1?key=${{ secrets.STEAM_API_KEY }}&format=${format}" -O "item_schema_${format}.txt"
            wget -U "TF2-Up-To-Date-Schema-Updater" "https://api.steampowered.com/IEconItems_440/GetSchemaOverview/v1?key=${{ secrets.STEAM_API_KEY }}&format=${format}" -O "schema_overview_${format}.txt"
            
            echo "files_same=false" >> $GITHUB_OUTPUT
            
            for language in "${Languages[@]}";
            do
              wget -U "TF2-Up-To-Date-Schema-Updater" "https://api.steampowered.com/IEconItems_440/GetSchemaItems/v1?key=${{ secrets.STEAM_API_KEY }}&format=${format}&language=${language}" -O "localized/item_schema_${format}_${language}.txt"
              wget -U "TF2-Up-To-Date-Schema-Updater" "https://api.steampowered.com/IEconItems_440/GetSchemaOverview/v1?key=${{ secrets.STEAM_API_KEY }}&format=${format}&language=${language}" -O "localized/schema_overview_${format}_${language}.txt"
            done

            sleep 10
          done

          items_game_url=$(sed -n 's/.*"\(http:\/\/media\.steampowered\.com\/apps\/440\/scripts\/items\/items_game[^"]*\)".*/\1/p' item_schema_json.txt)

          if ! [ -z "$items_game_url" ]; 
            then
              wget -U "TF2-Up-To-Date-Schema-Updater" "${items_game_url}" -O items_game_vdf.txt

              pip install vdf2json

              vdf2json items_game_vdf.txt items_game_json.txt -p
            fi
          fi
        working-directory: ${{ env.SCHEMA_PATH }}/files
      
      - name: Commit files
        if: steps.compare.outputs.files_same == 'false'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add *

          git commit -a -m "Update the schema"
        working-directory: ${{ env.SCHEMA_PATH }}/files

      - name: Push changes
        if: steps.compare.outputs.files_same == 'false'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 