name: Download new schema

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 16 * * *' # Runs every day at 16:00 UTC / 5 PM CET
  workflow_dispatch:
    
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set environment variables
        run: echo SCHEMA_PATH=$(pwd) >> $GITHUB_ENV
    
      - name: Compare & Download schema
        id: compare
        run: |
          wget "https://api.steampowered.com/IEconItems_440/GetSchemaItems/v1?key=${{ secrets.STEAM_API_KEY }}&format=json" -O item_schema_json_new.txt

          if ! [ -f item_schema_json.txt ] || ! cmp -s item_schema_json.txt item_schema_json_new.txt; 
          then
            echo "files_same=false" >> $GITHUB_OUTPUT

            mv item_schema_json_new.txt -f item_schema_json.txt
            wget "https://api.steampowered.com/IEconItems_440/GetSchemaItems/v1?key=${{ secrets.STEAM_API_KEY }}&format=vdf" -O item_schema_vdf.txt
            wget "https://api.steampowered.com/IEconItems_440/GetSchemaItems/v1?key=${{ secrets.STEAM_API_KEY }}&format=xml" -O item_schema_xml.txt
          else
            echo "files_same=true" >> $GITHUB_OUTPUT
          fi
        working-directory: ${{ env.SCHEMA_PATH }}
      
      - name: Commit files
        if: steps.compare.outputs.files_same == 'false'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add item_schema_json.txt
          git add item_schema_vdf.txt
          git add item_schema_xml.txt

          git commit -a -m "Update the schema"

      - name: Push changes
        if: steps.compare.outputs.files_same == 'false'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 